# Generated by Django 6.0.5 on 2026-05-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='services/default.jpg', null=True, upload_to='services/'),
        ),
    ]
