# Generated by Django 6.0.5 on 2026-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(default='2026-06-01'),
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.TimeField(default='12:00'),
        ),
    ]
