# Generated by Django 6.0.5 on 2026-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_status_alter_booking_email_and_more'),
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointment_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('appointment_date', 'appointment_time'), name='unique_appointment_slot'),
        ),
    ]
