# Generated by Django 6.0.5 on 2026-06-24 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
