# Generated by Django 6.0.5 on 2026-06-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('completed_count', models.IntegerField(default=0)),
                ('cancelled_count', models.IntegerField(default=0)),
                ('total_revenues', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='services.service')),
            ],
            options={
                'unique_together': {('date', 'service')},
            },
        ),
    ]
